#!/usr/bin/env python3
"""
generate_demo_bundle.py

Create a minimal Novara Evidence Bundle (.zip) for testing.
Output file (default):

  examples/hinata-2025-11-19.zip
"""

import json
import os
import uuid
import zipfile
from datetime import datetime, timezone
from pathlib import Path


def iso_now() -> str:
    """Return current time in ISO 8601 format with Z suffix."""
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def build_meta(bundle_id: str) -> dict:
    """Build meta.json content for the demo bundle."""
    return {
        "bundle_id": bundle_id,
        "version": "0.1",
        "created_at": iso_now(),
        "incident_time": "2025-11-19T12:34:56Z",
        "system_info": {
            "name": "Novara Demo Chatbot",
            "version": "demo-0.1",
            "operator": "Novara Developer (demo)"
        },
        "incident_summary": (
            "Demo bundle for Novara Evidence Bundle (v0.1). "
            "Hypothetical navigation / conversation incident for testing only."
        ),
        "tags": [
            "demo",
            "evidence-bundle",
            "novara",
            "example"
        ],
        "disclaimer": (
            "This is a DEMO bundle generated by generate_demo_bundle.py. "
            "Not real incident data."
        )
    }


def build_aal_lines(bundle_id: str) -> list[dict]:
    """Return a list of AAL entries that will be written as NDJSON."""
    return [
        {
            "bundle_id": bundle_id,
            "timestamp": "2025-11-19T12:34:00Z",
            "actor": "user",
            "action": "send_message",
            "input": {
                "text": "Please navigate me to the campus library."
            },
            "output": None,
            "metadata": {
                "channel": "mobile-app",
                "locale": "en-US"
            }
        },
        {
            "bundle_id": bundle_id,
            "timestamp": "2025-11-19T12:34:02Z",
            "actor": "route-planner",
            "action": "plan_route",
            "input": {
                "origin": "user-current-location",
                "destination": "Campus Library"
            },
            "output": {
                "route_id": "route-001",
                "eta_minutes": 12
            },
            "metadata": {
                "map_version": "2025-Q4-demo",
                "model": "nav-model-demo-001"
            }
        },
        {
            "bundle_id": bundle_id,
            "timestamp": "2025-11-19T12:34:05Z",
            "actor": "assistant",
            "action": "send_message",
            "input": {
                "route_id": "route-001"
            },
            "output": {
                "text": "I found a route to the campus library. It will take about 12 minutes."
            },
            "metadata": {
                "model": "gpt-demo-001",
                "temperature": 0.3
            }
        },
        {
            "bundle_id": bundle_id,
            "timestamp": "2025-11-19T12:40:00Z",
            "actor": "incident-reporter",
            "action": "log_event",
            "input": {
                "event_type": "user-report",
                "severity": "low"
            },
            "output": {
                "note": "User reported that the suggested route went through a temporarily closed gate."
            },
            "metadata": {
                "report_channel": "in-app",
                "ticket_id": str(uuid.uuid4())
            }
        }
    ]


def main() -> None:
    # Ensure examples/ directory exists
    examples_dir = Path("examples")
    examples_dir.mkdir(parents=True, exist_ok=True)

    # Fixed name for v0.1 demo bundle (matches README)
    bundle_path = examples_dir / "hinata-2025-11-19.zip"

    bundle_id = "hinata-2025-11-19-demo"
    meta = build_meta(bundle_id)
    aal_lines = build_aal_lines(bundle_id)

    # Build NDJSON string
    aal_ndjson = "\n".join(json.dumps(line, ensure_ascii=False) for line in aal_lines) + "\n"

    # Create ZIP bundle
    with zipfile.ZipFile(bundle_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        # meta.json
        zf.writestr("meta.json", json.dumps(meta, indent=2, ensure_ascii=False))

        # aal.ndjson
        zf.writestr("aal.ndjson", aal_ndjson)

        # Example attachment (prompt)
        zf.writestr(
            "attachments/prompt.txt",
            "User: Please navigate me to the campus library.\n"
            "System: This is a demo prompt for Novara Evidence Bundle v0.1.\n"
        )

    print(f"[OK] Demo bundle written to: {bundle_path}")


if __name__ == "__main__":
    main()